start_level: 0 #начальный уровень.
money_min: 0 #минимальное количество денег с одного клика(начальный уровень).
money_max: 2 #максимальное количество денег с одного клика(начальный уровень).
level_money: 1 #сколько будет добавляться денег. 
#К примеру:
#Было money_min: 0 и money_max: 2
#Стало money_min: 0 и money_max: 3
need_xp: 50 #сколько нужно опыта для повышения уровня.
max_level: 10 #максимальный уровень.
xp_min: 0 #минимальное количество опыта с одного клика (начальный уровень).
xp_max: 1 #максимальное количество опыта с одного клика (начальный уровень).
level_xp: 2 #сколько будет добавляться опыта.
#К примеру:
#Было xp_min: 0 и xp_max: 1
#Стало xp_min: 0 и xp_max: 3

form:
  title: "Ваша статистика"
  #Доступные теги:
  #level - уровень
  #xp - опыт
  #total - всего заработано денег на кликере
  #clicks - всего сделано кликов
  stats: "§c• §rУровень: §e{level}\n§c• §rОпыт: §e{xp}/50\n§c• §rВсего заработано: §e{total}\n§c• §rВсего сделано кликов: §e{clicks}"
  exit: "Выйти"
  
tip: "§bКликер §8> §e+{money}"
level_up: "§bКликер §8> §rПовышение уровня!"